% A script to read a csv dataset generated by script_GenerateDataset
% This is necessary because matlab is a P.O.S

dataset_path = '../datasets/test.csv'

mydata = import(dataset_path);

% import takes a while depending on size of csv file

headers = mydata{1}

